org.gradle.daemon=false
org.gradle.jvmargs=-Xmx3G
org.gradle.configureondemand=false

minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neoforge_version=21.1.233
neoforge_version_range=[21.1,)
mapping_version=2024.11.17

mod_id=openstuff
mod_name=OpenStuff
mod_group_id=gml.openstuff
mod_version=1.0.0
mod_license=MIT
mod_authors=Grahmindol
mod_description=Armor and stuff for OpenComputers.
loader_version_range=[4,)
opencomputers_version=1.9.4-2
opencomputers_version_range=[1.9.0,)
curse_project_id=231687
opencomputers_curse_project_id=1634364
scala_loader_version=3.3.3-build-15
